### ISSUE TITLE
FUNCION RADICACION

### ISSUE THREAD

**Issue by MaximilianoAnguloOliva** [ispc-programador2022/a1g4-t1#14]
7- función radicación, retorna la raiz del primero respecto del segundo parámetros.

def radicacion():
    num = int(input("Raíz cuadrada de:"))
    raiz = num** (1/2)
    print(raiz)
    print("La raiz cuadrada de", num , "es", raiz )

**Comment by Aukha00** [comment]
quedo finalizado
